name: Fifth Workflow Git Hab

# on: [push, issues, pull_request]
on: 
    issues:
        types: [edited, deleted]
    pull_request:
        types: [assigned, closed]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display Event Vars
              run: | 
                echo $GITHUB_SHA
                echo $GITHUB_REF
