name: Fourth Worflow Git Hub Atcions

on: 
    workflow_run:
        workflows: [Third Worflow Git Hub Atcions]
        types:
            - completed

jobs:
    success-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        steps:
            - name: Success Command
              run: echo "Success"

    failur-command:
        runs-on: ubuntu-lates
        if: ${{ github.event.workflow_run.conclusion == 'failure'}}
        steps:
            - name: Failure Command
              run: echo "Faild"
