name: Fourth Worflow Git Hub Atcions

on: 
    workflow_run:
        workflows: [Third Worflow Git Hub Atcions]
        types:
            - completed

jobs:
    hello-command:
        runs-on: ubuntu-latest
        steps:
            - name: Show all files
              run: echo "HEllo Dude!"
